Installer / autorun removed

diff --git a/ressources/autorun b/ressources/autorun
--- a/ressources/autorun
+++ b/ressources/autorun
@@ -17,6 +17,12 @@ CURRDIRINSTALLER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 LED=/karotz/bin/led
 
+function led_orange
+{
+  killall led
+  $LED -l $ORANGE
+}
+
 function led_orange_pulse {
     # killall led
     $LED -l FFA500 -p 000000 -d 700 &
@@ -37,7 +43,7 @@ function SAY {
 }
 
 function LOG {
-    echo $1 >> ${CURRDIRINSTALLER}/logautorun.txt
+    echo $(date +"%m-%d-%Y %H-%M-%S") $1 >> ${CURRDIRINSTALLER}/logautorun.txt
 }
 
 function ERROR {
@@ -62,25 +68,91 @@ killall madplay
 cp -r ${CURRDIRINSTALLER}/sound/*.mp3 /tmp/
 ls /tmp
 
-SAY "Karotz_SFX_USB"
-
 if [ -f ${CURRDIRINSTALLER}/updatedone ]; then
     LOG "[USBKEY] ## UPDATE ALREADY DONE"
     exit 0
 fi
 
-
-cd $(dirname $0)
-
+# Music time
+SAY "Karotz_SFX_USB"
 led_orange_pulse
 
-# Installing
-LOG "Installing"
+# Override generated rootfs image
+if [ ! -e "${CURRDIRINSTALLER}/rootfs.img.gz" ]; then
+ echo "ERROR: Unable to find rootfs file"
+ LOG "ERROR: Unable to find rootfs file"
+ led_red
+ SAY "error"
+ exit 1
+fi
+
+if [ ! -e "${CURRDIRINSTALLER}/rootfs.img.gz.md5" ]; then
+  echo "ERROR: Unable to find rootfs signature file"
+  LOG "ERROR: Unable to find rootfs signature file"
+  led_red
+  SAY "error"
+  exit 1
+fi
+
+SIGN=$(md5sum ${CURRDIRINSTALLER}/rootfs.img.gz | cut -d' ' -f1)
+REF=$(cat ${CURRDIRINSTALLER}/rootfs.img.gz.md5 | cut -d' ' -f1) 
+
+echo "Computed  MD5 :"$SIGN
+echo "Reference MD5 :"$REF
+
+if [ "$SIGN" == "$REF" ]; then
+  echo "Check : Success"
+  LOG "Check success"
+  echo "Start Flashing"
+else
+  echo "Check : Failed"
+  LOG "ERROR: check failed $SIGN - $REF"
+  echo "Flashing Aborted"
+  led_red
+  SAY "error"
+  exit 1
+fi
+
+led_orange
+LOG "Installing rootfs"
+
+echo "Erasing Flash"
+LOG "Erasing Flash"
+/sbin/flash_eraseall /dev/mtd2
+
+echo "Flashing new firmware"
+LOG "Flashing Firmware"
+/sbin/nandwrite -pm /dev/mtd2 ${CURRDIRINSTALLER}/rootfs.img.gz
+LOG "Flashing Firmware done"
+
+sleep 20
+
+# Configuration for HTTPD, out of rootfs
+if [ ! -f /usr/httpd.conf ]; then
+  LOG "Installing httpd.conf file"
+  cp ${CURRDIRINSTALLER}/conf/httpd.conf /usr/
+  chown root.root /usr/httpd.conf
+fi
+
+if [ ! -d /usr/www/ ]; then
+  LOG "Creating /usr/www/"
+  mkdir -p /usr/www/
+  echo "It Works !!!" > /usr/www/index.html
+  chown -R 51.51 /usr/www/
+fi
+
+
+
+led_orange_pulse
+# Installing Web App
+cd ${CURRDIRINSTALLER}
+
+LOG "Installing Web App"
 bash ${CURRDIRINSTALLER}/openkarotz/install
 
-LOG "GREEN"
+LOG "Web App installation end"
 led_green
-sleep 2
+sleep 3
 
 LOG "[USBKEY] ## All done. Rebooting."
 SAY "Karotz_SFX_OK"
